"""add_ai_models_leads_recommendations_api_settings

Revision ID: c69121a8668d
Revises: 874c0cb20851
Create Date: 2026-05-14 23:34:15.434151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c69121a8668d'
down_revision: Union[str, Sequence[str], None] = '874c0cb20851'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('key_name', sa.String(length=200), nullable=False),
    sa.Column('encrypted_value', sa.Text(), nullable=True),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_name')
    )
    op.create_table('leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('original_message', sa.Text(), nullable=False),
    sa.Column('parsed_needs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_location', sa.String(length=500), nullable=True),
    sa.Column('budget_min', sa.Integer(), nullable=True),
    sa.Column('budget_max', sa.Integer(), nullable=True),
    sa.Column('bedroom_count', sa.Integer(), nullable=True),
    sa.Column('pet_required', sa.Boolean(), nullable=True),
    sa.Column('preferred_transport', sa.String(length=50), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_agent_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('distance_meters', sa.Integer(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('route_mode', sa.String(length=20), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('reason_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_message', sa.Text(), nullable=True),
    sa.Column('sent_to_customer', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_table('leads')
    op.drop_table('api_settings')
    # ### end Alembic commands ###
